package controller;

public enum MenuCommands {
	APP_QUIT, SHOW_LIST_WAREHOUSE, SHOW_DETAIL_WAREHOUSE, 
	ADD_WAREHOUSE,DELETE_WAREHOUSE,DELETE_PART,ADD_PART,
	SHOW_DETAIL_PART,SHOW_LIST_PARTS,SHOW_DETAIL_WAREHOUSE_PART,
	
}
